flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    TextAreaField,
)
from wtforms.validators import DataRequired


class NEW_POST(FlaskForm):
    title = StringField(
        "Title", validators=[DataRequired(message="Post title  is required.")]
    )

    content = TextAreaField(
        "Post Content", validators=[DataRequired(message="Post Content is required.")]
    )

    post = SubmitField("post")


class EDIT_POST(FlaskForm):
    title = StringField(
        "Title", validators=[DataRequired(message="Post title  is required.")]
    )

    content = TextAreaField(
        "Post Content", validators=[DataRequired(message="Post Content is required.")]
    )

    edit_post = SubmitField("update")

flaskblog/posts/routes.py
from flask import Blueprint, redirect, render_template, url_for, abort, flash, request, jsonify
from flaskblog.posts.forms import NEW_POST, EDIT_POST
from flaskblog.models import Post, db
from flask_login import current_user, login_required
from sqlalchemy import desc

posts = Blueprint("posts", __name__)


@posts.route("/create-post", methods=["GET", "POST"])
@login_required
def create_post():
    print('just arived in the create-post')

    if request.method == 'POST':

        print('i am here in the post method')
        category = request.args.get('category')
        print('this is the request args',request.args)
        print('this is the category', category)
        print('inside the post, where is the category', category)
        post_title = request.get_json().get('postTitle').strip()
        post_content = request.get_json().get('postContent').strip()
        post_category = request.args.get('category').strip()
        user_post = Post(
            title=post_title,
            content=post_content,
            user_id=current_user.id,
            category = post_category.capitalize(),
            author=current_user
        )

        db.session.add(user_post)
        db.session.commit()

        return jsonify({'status': 'success', 'message': 'Post was successfully created!', 'redirect_url': url_for('main.index_page')}), 200

    return render_template("post.html")



# filter posts
@posts.route("/filter_posts", strict_slashes=False, methods=['GET'])
def filter_posts():
    if 'category' in request.args:
        category = request.args.get('category').strip()
        print('this is category', len(category))

        posts = Post.query.filter_by(category=category).all()
        if (posts):

            print('all post', posts)
            posts_array = []
            for post in posts:
                print('post_title', post.title)
                post_data = {
                    'title': post.title,
                    'content': post.content,
                    'created_at':post.date_posted.strftime('%d%b %Y').capitalize(),
                    'author': post.author.username,
                    'post_id': post.id,
                    'edit_url': url_for('posts.edit_post', post_id=post.id),
                    'delete_url': url_for('posts.delete_post', post_id=post.id)
                }

                posts_array.append(post_data)

            return jsonify({'posts': posts_array}), 200
        else:
             return jsonify({
                'status': 'error', 
                'message': f'No posts were found under the category "{category}". Please check other categories'
            }), 404
    else:
        print('this is me in the else block')
        posts = Post.query.order_by(desc(Post.date_posted)).all()
        if posts:
            posts_array = []
            for post in posts:
                print('post_title', post.title)
                post_data = {
                    'title': post.title,
                    'content': post.content,
                    'created_at':post.date_posted.strftime('%d%b %Y').capitalize(),
                    'author': post.author.username,
                    'post_id': post.id,
                    'edit_url': url_for('posts.edit_post', post_id=post.id),
                    'delete_url': url_for('posts.delete_post', post_id=post.id)
                }
                posts_array.append(post_data)

            return jsonify({'status': 'success', 'posts': posts_array}), 200
        else:
            return jsonify({'status': 'error', 'message': 'No posts were found, Try creating a new post'}), 404


@posts.route("/edit-post/<int:post_id>", methods=["GET", "PUT", "POST"])
@login_required
def edit_post(post_id):


    user_post = Post.query.get_or_404(post_id)
    if user_post.author != current_user:
        abort(403)

    if request.method == 'PUT':
        print('Handling PUT request')
        try:
            user_post.title = request.get_json().get('postTitle').strip()
            user_post.content = request.get_json().get('postContent').strip()
            db.session.commit()
            return jsonify({'status': 'success', 'message': 'Your post was successfully updated', 'redirect_url': url_for('main.index_page')}), 200
        except Exception as e:
            return jsonify({'status': 'error', 'message': str(e)}), 500

    return render_template("edit_post.html", post_id=post_id)




@posts.route('/post-details/<int:post_id>', methods=['GET'])
def post_details(post_id):
    print('hellow from details')
    post = Post.query.get_or_404(post_id)
    return jsonify({'status': 'success', 'post_title': post.title, 'post_content': post.content}), 200


@posts.route("/delete/<int:post_id>", methods=["GET", "POST"])
def delete_post(post_id):

    user_post = Post.query.get_or_404(post_id)

    db.session.delete(user_post)

    db.session.commit()

    return redirect(url_for("main.index_page"))

flaskblog/users/routes.py
from flask import Blueprint, redirect, flash, url_for, render_template, session, request, current_app, jsonify
from flask_login import current_user, logout_user, login_user, login_required
from werkzeug.utils import secure_filename
from uuid import uuid4
import os
from flaskblog.users.forms import (
    Register_Form,
    Login_Form,
    Update_Account_Form,
    Reset_Request_Form,
    Reset_Password,
)
from flaskblog.users.utils import send_email
from flaskblog.models import User
from flaskblog import bcrypt, db


users = Blueprint("users", __name__)


# User Registration route
@users.route("/register", strict_slashes=False, methods=["GET", "POST"])
def register_page():
    if current_user.is_authenticated:
        return redirect("index_page")
    
    #  check if request is Post
    if request.method == "POST":
        print(f"Content-Type: {request.content_type}")

        print(f"Content-Type: {request.content_type}")
        print(f"Request Data: {request.data}")

        if request.content_type != 'application/json':
            print(f"Content-Type: {request.content_type}")
            return jsonify({'error': 'Unsupported Media Type'}), 415
        # convert to dictionary
        data = request.get_json()

        # extract credentials
        username = data.get('username')
        email = data.get('email')

        # validate user credentials does not exists before attempting to persist to db.

        # declare an empty dictionary for error handling
        errors = {}


        if User.query.filter_by(username=username).first() and User.query.filter_by(email=email).first():
            errors['username_and_email_taken'] = 'Username already exists and Email already registered, Please choose a different ones'
        elif User.query.filter_by(username=username).first():
            errors['username_taken'] = 'Username already exists. Please choose a different one.'

        elif User.query.filter_by(email=email).first():
            errors['email_taken'] = 'Email already registered. Please use a different email address.'


        if errors:
            print(errors)
            return jsonify({'errors': errors})
        
        # save user in the database.
        user = User(
            username= data.get('username'),
            email= data.get('email'),
            password=bcrypt.generate_password_hash(data.get('password')).decode("utf-8"),
        )
        db.session.add(user)
        db.session.commit()
        db.session.close()

        return jsonify({"welcome_message": 'Thank you for Joining us', 'redirect_url': url_for('users.login_page'), 'username': data.get('username')})
    else:
        return render_template("register.html")


# User Login Route
@users.route("/login", strict_slashes=False, methods=["GET", "POST"])
def login_page():
    print('login paguihiuhe')
    if current_user.is_authenticated:
        return redirect(url_for("main.index_page"))
    """
    Get users email from form email field
    Check if  email exists in database
    if email exists:
        User has account in our database
        Unhash the password of the user
        Compare the the unhashed password with the form password.
        if Match:
            Login the User in, add remember me field.
    """
    # form = Login_Form()
    if request.method == 'POST':
        data = request.get_json()

        email = data.get('email')
        password = data.get('password')

        print('user email', email)
        print('user password', password)
        user = db.session.query(User).filter_by(email=email).first()
        if user and bcrypt.check_password_hash(user.password, password):

            # log the user in using session object from flask
            login_user(user)

            return jsonify({'status':'success','login_message': f"Success! You're logged in and ready to go, {user.username}", 'redirect_url': url_for('main.index_page')}), 200
                            

        else:
            return jsonify({"status": 'failure', 'login_message': 'Invalid username or password'}), 400


    return render_template("login.html")


@users.route("/account", methods=["GET", "POST"])
@login_required
def account_page():
    form = Update_Account_Form()

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data

        # update profile pic.
        if form.profile_pic.data:
            profile_pic_filname = secure_filename(form.profile_pic.data.filename)

            _, file_ext = os.path.splitext(profile_pic_filname)

            random_filename = f"{uuid4()}{file_ext}"

            profile_pic_ = os.path.join(current_app.config["UPLOAD_FOLDER"], random_filename)
            form.profile_pic.data.save(profile_pic_)
            current_user.image_file = random_filename
        try:
            db.session.commit()
            flash('Your account was successfully Updated', 'success')
        except Exception as e:
            db.session.rollback()
            flash(f"An error occured {e}")
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    img_file = url_for("static", filename="profile_pics/" + "default.jpg")
    return render_template("account.html", form=form, img_file=img_file)


# logout route
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index_page"))


# Send TOTP for reseting email.
@users.route("/reset-password", methods=["GET", "POST"])
def send_email_link():
    form = Reset_Request_Form()
    if request.method == "POST":
            print('useremail', request.get_json().get('email'))
            user = db.session.query(User).filter_by(email=request.get_json().get('email')).first()
            print(user)
            if user:

                # call the send maiil function
                send_email(user)

                flash(
                    "Email sent successfully!, follow link to reset your password",
                    category="success",
                )
               
                return jsonify({'status': 'success', 'message':"Email sent successfully!, follow link to reset your password"}), 200
            else:
                return jsonify({'status': 'failure', 'message':"Email does not exist in our system"}), 400

    return render_template("reset_email.html")


# Password Reset
@users.route("/reset-password/<string:token>", methods=["GET", "POST"])
def reset_password(token):
    user = User.validate_token(token, expire_sec=300)

    print('inside the reset password link')

    if request.method == "POST":
        print('inside post reset password, naa me dee for here')
        # user variable would be None if the time set on the link expires.
        if user is None:
            return jsonify(
                {
                    'status': 'error',
                    'message': 'The reset link is either invalid or has expired. Please request a new password reset.',
                    'redirect_url': url_for("users.send_email_link")
                }
            ), 400

        #  hash user password
        user.password = bcrypt.generate_password_hash(request.get_json().get('password')).decode(
            "utf-8"
        )

        # # update user password.
        db.session.commit()
        return jsonify(
            {
                'status': 'success',
                'message': 'Your password has been successfully reset. You can now log in with your new password. redirecting....',
                'redirect_url': url_for("users.login_page")
            }
        ), 200

    # render reset password template on GET REQUEST.
    return render_template("reset_password.html")

flaskblog/templates/about.html
{% extends 'base.html' %}
{% block title %} Flask-Blog About page {% endblock %}

flaskblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>

    {% block style %}
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    {% endblock %}

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet"
    />

    <!-- Font Awesome CDN -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      integrity="sha512-..."
      crossorigin="anonymous"
    />
  </head>
  <body>
    <!-- HEADER -->
    <header class="header">
      <nav class="base-nav">
        <ul class="menu-list">
          <li>
            <a href="{{ url_for('main.index_page') }}">
              NARRATIV <i class="fas fa-book"></i>
            </a>
          </li>
        </ul>

        <ul class="user-action hide-dropdown">
          {% if current_user.is_authenticated %}
          <li>
            <a href="{{ url_for('posts.create_post') }}">
              <i class="fas fa-pencil-alt"></i> New Post
            </a>
          </li>

          <li>
            <a href="{{ url_for('users.account_page') }}">
              <i class="fas fa-user"></i> Profile
            </a>
          </li>
          <li>
            <a href="{{ url_for('users.logout') }}">
              <i class="fas fa-sign-out-alt"></i> Logout
            </a>
          </li>
          {% else %}
          <li>
            <a href="{{ url_for('users.login_page') }}">
              <i class="fas fa-sign-in-alt"></i> Sign in
            </a>
          </li>
          <li>
            <a href="{{ url_for('users.register_page') }}">
              <i class="fas fa-user-plus"></i> Sign up
            </a>
          </li>

          {% endif %}
        </ul>
        <!-- hand burger -->
        <div class="mobile-handburger">
          <i class="fas fa-bars"></i>
        </div>
      </nav>
    </header>

    <!-- FLASH MESSAGES -->

    <!-- MAIN CONTENT -->
    {% block content %} {% endblock %}

    <custom-footer></custom-footer>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

    <!-- <script src="{{ url_for('static', filename='js/script.js') }}"></script> -->
  </body>
</html>

flaskblog/templates/edit_post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <!-- FONT AWESOME LINK -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/edit_post.css') }}"
    />
  </head>
  <body>
    <!-- HEADER -->
    <header class="post-header">
      <nav class="nav">
        <ul class="nav__left">
          <li>
            <a href="{{ url_for('main.index_page') }}">
              Simple Blog <i class="fas fa-book"></i>
            </a>
          </li>
        </ul>

        <ul class="nav__right">
          <button class="publish" type="submit">Publish</button>
          <li>
            <a href="{{ url_for('users.account_page') }}">
              <i class="fas fa-user"></i> Account
            </a>
          </li>

          <li>
            <a href="{{ url_for('users.logout') }}">
              <i class="fas fa-sign-out-alt"></i> Logout
            </a>
          </li>

          <!-- hand burger -->
          <div class="mobile-handburger">
            <i class="fas fa-bars"></i>
          </div>
        </ul>
      </nav>
    </header>

    <div class="feedback feedback--success">
      <i class="fas fa-check-circle"></i>
      <span></span>
    </div>

    <!-- MAIN SECTION -->
    <section class="post-container">
      <form action="/post/new" method="post" class="post-article" novalidate>
        <div class="form">
          <input
            type="text"
            id="title"
            name="title"
            placeholder="Title"
            class="title-input"
          />
          <textarea
            id="content"
            name="body"
            placeholder="Tell your story..."
            class="body-textarea"
          ></textarea>
        </div>
      </form>
    </section>

    <!-- FOOTER -->
    <custom-footer></custom-footer>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

    <script src="{{ url_for('static', filename='js/edit_post.js') }}"></script>
  </body>
</html>

flaskblog/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Narrativ</title>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/home.css') }}"
    />
    <script id="current_user" type="application/json" defer>
      {{ user_data | tojson | safe }}
    </script>
  </head>
  <body>
    <!-- HEADER -->
    <header class="header">
      <nav class="base-nav">
        <ul class="menu-list">
          <li>
            <a href="{{ url_for('main.index_page') }}">
              NARRATIV <i class="fa-brands fa-blogger-b"></i>
            </a>
          </li>
        </ul>
        <!-- Added closing tag -->
        <ul class="user-action hide-dropdown">
          <!-- display only when the current user is signed in -->
          {% if current_user.is_authenticated %}
          <li class="signin-style">
            <a href="{{ url_for('posts.create_post') }}">
              <i class="fas fa-pencil-alt"></i> New Post
            </a>
          </li>
          <li class="signin-style">
            <a href="{{ url_for('users.account_page') }}">
              <i class="fas fa-user"></i> Profile
            </a>
          </li>

          <li class="signin-style">
            <a href="{{ url_for('users.logout') }}">
              <i class="fas fa-sign-out-alt"></i> Logout
            </a>
          </li>

          {% else %}
          <!-- display only when the user is signed out -->
          <li class="signin-style">
            <a href="{{ url_for('users.login_page') }}">
              <i class="fas fa-sign-in-alt"></i> Sign in
            </a>
          </li>
          <li class="signin-style">
            <a href="{{ url_for('users.register_page') }}">
              <i class="fas fa-user-plus"></i> Sign up
            </a>
          </li>
          {% endif %}
          <!-- display only when the user is signed out -->
        </ul>

        <!-- hamburger -->
        <div class="mobile-handburger">
          <i class="fas fa-bars"></i>
        </div>
      </nav>
    </header>

    <!-- FEEDBACK -->
    <div class="feedback feedback--success">
      <i class="fas fa-check-circle"></i>
      <span></span>
    </div>

    <section class="home-section">
      <div class="home-container">
        <article class="home-article">
          <!-- Display posts -->
        </article>

        <aside class="aside-content">
          <!-- <div class="for-you">
            <h1>For You page</h1> 
            <p class="latest-post">
              <i class="fas fa-newspaper"></i>
              Latest Post
            </p>
          </div> -->

          <h2 class="categories">Post Categories</h2>
          <div class="post-recommendation">
            <p><i class="fas fa-laptop-code"></i> Technology</p>
            <p><i class="fas fa-couch"></i> Lifestyle</p>
            <p><i class="fas fa-book-open"></i> Education</p>
            <p><i class="fas fa-film"></i> Entertainment</p>
            <p><i class="fas fa-code"></i> Programming</p>
            <p><i class="fas fa-utensils"></i> Food & Drink</p>
          </div>
          <!-- <button class="add-more">
            <i class="fas fa-plus"></i>
            Add More
          </button> -->
        </aside>
      </div>
    </section>

    <div class="delete-modal hide-modal">
      <div class="delete-modal-content">
        <div class="delete-title">
          <h2>Are you sure you want to delete this post?</h2>
          <button
            title="Cancel Delete"
            class="cancel-delete-modal cancel-delete-icon"
          >
            <i class="fa fa-times"></i>
          </button>
        </div>
        <p>This post will be permanently removed and cannot be recovered.</p>
        <div class="delete-cta">
          <form method="post" class="delete_form">
            <button type="submit" class="confirm-delete-btn">Confirm</button>
            <button type="button" class="cancel-delete-modal">Cancel</button>
          </form>
        </div>
      </div>
    </div>

    <custom-footer></custom-footer>

    <!-- <script src="{{ url_for('static', filename='js/home.js') }}"></script> -->
    <!-- <script src="{{ url_for('static', filename='js/post.js') }}"></script> -->

    <script
      src="{{ url_for('static', filename='js/script.js') }}"
      type="module"
    ></script>
  </body>
</html>

flaskblog/templates/post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <!-- FONT AWESOME LINK -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/post.css') }}"
    />
  </head>
  <body>
    <!-- HEADER -->
    <header class="post-header">
      <nav class="nav">
        <ul class="nav__left">
          <li>
            <a href="{{ url_for('main.index_page') }}">
              NARRATIV <i class="fas fa-book"></i>
            </a>
          </li>
        </ul>

        <ul class="nav__right">
          <button class="publish" type="submit">Publish</button>
          <div class="user-action hide-dropdown">
            <li>
              <a href="{{ url_for('users.account_page') }}">
                <i class="fas fa-user"></i> Account
              </a>
            </li>

            <li>
              <a href="{{ url_for('users.logout') }}">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
            </li>
          </div>

          <!-- hand burger -->
          <div class="mobile-handburger">
            <i class="fas fa-bars"></i>
          </div>
        </ul>
      </nav>
    </header>

    <!-- MAIN SECTION -->
    <section class="post-container">
      <form action="/post/new" method="post" class="post-article" novalidate>
        <div class="form">
          <input
            type="text"
            id="title"
            name="title"
            placeholder="Title"
            class="title-input"
          />
          <textarea
            id="content"
            name="body"
            placeholder="Tell your story..."
            class="body-textarea"
          ></textarea>
        </div>
      </form>
    </section>

    <!-- FOOTER -->
    <custom-footer></custom-footer>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

    <script src="{{ url_for('static', filename='js/post.js') }}"></script>
  </body>
</html>

flaskblog/templates/reset_email.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/reset_email.css') }}"
    />

    <!-- font awsome icon -->

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      integrity="sha512-..."
      crossorigin="anonymous"
    />

    <!-- title -->
    <title>NARRATIV-reset password</title>
  </head>
  <body>
    <header class="header">
      <nav class="base-nav">
        <ul class="menu-list">
          <li>
            <a href="{{ url_for('main.index_page') }}">
              NARRATIV <i class="fas fa-book"></i>
            </a>
          </li>
        </ul>

        <ul class="user-action hide-dropdown">
          {% if current_user.is_authenticated %}
          <li>
            <a href="{{ url_for('posts.create_post') }}">
              <i class="fas fa-pencil-alt"></i> New Post
            </a>
          </li>

          <li>
            <a href="{{ url_for('users.account_page') }}">
              <i class="fas fa-user"></i> Profile
            </a>
          </li>
          <li>
            <a href="{{ url_for('users.logout') }}">
              <i class="fas fa-sign-out-alt"></i> Logout
            </a>
          </li>
          {% else %}
          <li>
            <a href="{{ url_for('users.login_page') }}">
              <i class="fas fa-sign-in-alt"></i> Sign in
            </a>
          </li>
          <li>
            <a href="{{ url_for('users.register_page') }}">
              <i class="fas fa-user-plus"></i> Sign up
            </a>
          </li>

          {% endif %}
        </ul>
      </nav>
      <div class="spinner-container">
        <div class="spinner"></div>
      </div>
    </header>

    <div class="feedback feedback--success">
      <i class="fas fa-check-circle"></i>
      <span>hellow</span>
    </div>
    <section class="reset-section">
      <h2 class="email-label">Enter your email</h2>
      <form class="reset-form" novalidate>
        <div class="reset-container">
          <input
            type="text"
            id="email"
            title="Email"
            placeholder="Enter your email"
          />
          <button>send</button>
        </div>
      </form>

      <script src="{{ url_for('static', filename='js/reset_email.js') }}"></script>
    </section>
  </body>
</html>

flaskblog/templates/reset_password.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Reset Password</title>

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/reset_password.css') }}"
    />
  </head>

  <!-- font awesome link -->
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
  />

  <body>
    <header class="header">
      <nav class="base-nav">
        <ul class="menu-list">
          <li>
            <a href="{{ url_for('main.index_page') }}">
              NARRATIV <i class="fas fa-book"></i>
            </a>
          </li>
        </ul>
        <!-- Added closing tag -->
        <ul class="user-action hide-dropdown">
          <!-- display only when the current user is signed in -->
          {% if current_user.is_authenticated %}
          <li>
            <a href="{{ url_for('posts.create_post') }}">
              <i class="fas fa-pencil-alt"></i> New Post
            </a>
          </li>
          <li>
            <a href="{{ url_for('users.account_page') }}">
              <i class="fas fa-user"></i> Profile
            </a>
          </li>

          <li>
            <a href="{{ url_for('users.logout') }}">
              <i class="fas fa-sign-out-alt"></i> Logout
            </a>
          </li>

          {% else %}
          <!-- display only when the user is signed out -->
          <li>
            <a href="{{ url_for('users.login_page') }}">
              <i class="fas fa-sign-in-alt"></i> Sign in
            </a>
          </li>
          <li>
            <a href="{{ url_for('users.register_page') }}">
              <i class="fas fa-user-plus"></i> Sign up
            </a>
          </li>
          {% endif %}
          <!-- display only when the user is signed out -->
        </ul>
      </nav>

      <!-- SPINNER -->
      <div class="spinner-container">
        <div class="spinner"></div>
      </div>
    </header>

    <div class="feedback feedback--success">
      <i class="fas fa-check-circle"></i>
      <span>hellow</span>
    </div>
    <section class="register-section">
      <form method="POST" class="register-form-container" novalidate id="form">
        <legend>Reset Password</legend>
        <input type="hidden" name="csrf_token" value="your_csrf_token_here" />
        <div class="register-form-content">
          <div class="input-group">
            <input
              type="password"
              name="password"
              placeholder="New Password"
              class="password"
            />
            <!-- Uncomment the next lines to display an error message -->
            <!-- <p class="form-error-message">Password error message</p> -->
          </div>
          <div class="input-group">
            <input
              type="password"
              name="confirm_password"
              placeholder="Confirm Password"
              class="confirm-password"
            />
            <!-- Uncomment the next lines to display an error message -->
            <!-- <p class="form-error-message">Confirm Password error message</p> -->
          </div>
        </div>
        <div class="form-action">
          <button type="submit" class="reset-btn">Reset Password</button>
        </div>
      </form>
    </section>

    <custom-footer></custom-footer>
    <!-- script -->
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script src="{{ url_for('static', filename='js/reset_password.js') }}"></script>
  </body>
</html>